# Generated by Django 4.1.5 on 2023-01-13 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('europe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='destinaton',
            new_name='destination',
        ),
    ]
