# Generated by Django 3.2.16 on 2023-01-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='session',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
